# Generated by Django 3.1 on 2020-08-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('political_news', 'Political News'), ('fiction', 'Fiction'), ('sports', 'Sports'), ('music', 'Music'), ('art', 'Art'), ('fashion', 'Fashion'), ('movies', 'Movies'), ('science', 'Science'), ('health', 'Health')], default='political_news', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
