# Generated by Django 3.1 on 2020-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torieeblog', '0002_blogpost_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
